In [2]:
import pandas as pd

In [33]:
df_hospital = pd.read_csv("./data/서울시 병의원 위치 정보.csv", encoding="cp949")

df_hospital.head()

,기관ID,주소,병원분류,병원분류명,응급의료기관코드,응급의료기관코드명,응급실운영여부(1/2),비고,기관설명상세,간이약도,...,진료시간(목요일)S,진료시간(금요일)S,진료시간(토요일)S,진료시간(일요일)S,진료시간(공휴일)S,우편번호1,우편번호2,병원경도,병원위도,작업시간
0,A1120837,"서울특별시 금천구 벚꽃로 286, 삼성리더스타워 111~114호 (가산동)",C,의원,G099,응급의료기관 이외,2,"외과: 상시진료, 내과는 당분간 휴진","서울시 송파구 문정동 장지동 법조단지 위례 가락동 가락시장역 위치, 삼성서울병원 외...",방이역 1번출구 바로옆 굿모닝 신한증권 뒷건물,...,900,900,900.0,1000.0,1000.0,85,11,126.884122,37.480394,2022-04-07 14:55:00.0
1,A1104130,"서울특별시 강남구 도산대로 118 (논현동, 신사빌딩 2층)",C,의원,G099,응급의료기관 이외,2,비만클리닉,"365일 진료, 국민건강보험공단 검진 지정병원 점심시간 13~14시",신사역 1번 출구 인근,...,1100,1100,1100.0,900.0,900.0,60,38,127.021809,37.516604,2021-06-07 14:54:49.0
2,A1124291,서울특별시 강남구 봉은사로 612 (삼성동),B,병원,G099,응급의료기관 이외,2,08/15 광복절 휴무,NaN,연신내역 3번 출구 연신내메디컬센터,...,900,900,900.0,900.0,NaN,61,70,127.062147,37.514281,2025-01-07 15:10:29.0
3,A1125194,"서울특별시 서초구 강남대로 509, 하늘안과 B동 7층 (반포동)",C,의원,G099,응급의료기관 이외,2,"점심시간 12:00~14:00 매주 목요일은 방문진료 둘째,넷째, 다섯째 토요일은 휴진","건강검진센터, 내과진료만 가능",광화문역 1번출구 세종아파트 내,...,1000,1000,1000.0,900.0,900.0,65,36,127.022492,37.507645,2025-01-07 15:10:29.0
4,A1117873,"서울특별시 관악구 신원로 38, 5층 (신림동, 청암빌딩)",N,치과의원,G099,응급의료기관 이외,2,대표번호1 지역번호 추가20170118150453,"서울시 송파구 문정동 장지동 법조단지 위례 가락동 가락시장역 위치, 삼성서울병원 외...",서월치안센터 인근 청암빌딩 5층,...,1400,1000,1000.0,1000.0,1000.0,87,76,126.929377,37.481918,2022-01-07 14:54:55.0

In [38]:
df_subway = pd.read_csv("./data/한국철도공사_역 위치 정보_20240401.csv", encoding="cp949")
df_busStop = pd.read_csv("./data/국토교통부_전국 버스정류장 위치정보_20241028.csv", encoding="cp949")

In [34]:
df_hos = df_hospital[["기관명"]]
df_hos.head()

             기관명
0        가산기대찬의원
1        365엠씨의원
2  (의)가산의료재단광동병원
3          000의원
4        가로수치과의원

In [35]:
df_hos["병원경도"] = df_hospital["병원경도"]
df_hos["병원위도"] = df_hospital["병원위도"]
df_hos["주소"] = df_hospital['주소']
df_hos["대표전화"] = df_hospital['대표전화1']
df_hos["진료시간(월요일)S"] = df_hospital["진료시간(월요일)S"]
df_hos.head()

C:\Users\user\AppData\Local\Temp\ipykernel_13908\1397967002.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hos["병원경도"] = df_hospital["병원경도"]
C:\Users\user\AppData\Local\Temp\ipykernel_13908\1397967002.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hos["병원위도"] = df_hospital["병원위도"]
C:\Users\user\AppData\Local\Temp\ipykernel_13908\1397967002.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hos["주소"] = df_hospital['주소']
C:\Users\user\AppData\Local\Temp\ipykernel_13908\1397967002.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hos["대표전화"] = df_hospital['대표전화1']
C:\Users\user\AppData\Local\Temp\ipykernel_13908\1397967002.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hos["진료시간(월요일)S"] = df_hospital["진료시간(월요일)S"]

,기관명,병원경도,병원위도,주소,대표전화,진료시간(월요일)S
0,가산기대찬의원,126.884122,37.480394,"서울특별시 금천구 벚꽃로 286, 삼성리더스타워 111~114호 (가산동)",02-6267-2580,900
1,365엠씨의원,127.021809,37.516604,"서울특별시 강남구 도산대로 118 (논현동, 신사빌딩 2층)",02-516-3650,1100
2,(의)가산의료재단광동병원,127.062147,37.514281,서울특별시 강남구 봉은사로 612 (삼성동),02-2222-4888,900
3,000의원,127.022492,37.507645,"서울특별시 서초구 강남대로 509, 하늘안과 B동 7층 (반포동)",02-6241-0001,1000
4,가로수치과의원,126.929377,37.481918,"서울특별시 관악구 신원로 38, 5층 (신림동, 청암빌딩)",02-882-2750,1000

In [36]:
df_hos["진료시간(월요일)C"] = df_hospital["진료시간(월요일)C"]
df_hos.head()

C:\Users\user\AppData\Local\Temp\ipykernel_13908\307059942.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hos["진료시간(월요일)C"] = df_hospital["진료시간(월요일)C"]

,기관명,병원경도,병원위도,주소,대표전화,진료시간(월요일)S,진료시간(월요일)C
0,가산기대찬의원,126.884122,37.480394,"서울특별시 금천구 벚꽃로 286, 삼성리더스타워 111~114호 (가산동)",02-6267-2580,900,1930
1,365엠씨의원,127.021809,37.516604,"서울특별시 강남구 도산대로 118 (논현동, 신사빌딩 2층)",02-516-3650,1100,2000
2,(의)가산의료재단광동병원,127.062147,37.514281,서울특별시 강남구 봉은사로 612 (삼성동),02-2222-4888,900,1800
3,000의원,127.022492,37.507645,"서울특별시 서초구 강남대로 509, 하늘안과 B동 7층 (반포동)",02-6241-0001,1000,2000
4,가로수치과의원,126.929377,37.481918,"서울특별시 관악구 신원로 38, 5층 (신림동, 청암빌딩)",02-882-2750,1000,1900

In [37]:
df_hos.to_csv("./data/hospital.csv", index=False)

In [25]:
df_subway.head()

   지역본부   역명        위도        경도  출입구 개수
0  서울본부   서울  37.55473  126.9708       3
1  서울본부   용산  37.52991  126.9648       3
2  서울본부   수색  37.58060  126.8959       1
3  서울본부   행신  37.36450  126.4952       2
4  서울본부  도라산  37.89877  126.7098       1

In [40]:
df_subway = df_subway[df_subway["지역본부"].str.contains('서울본부|수도권광역', na=False, case=False)]
df_subway.head()

   지역본부   역명        위도        경도  출입구 개수
0  서울본부   서울  37.55473  126.9708       3
1  서울본부   용산  37.52991  126.9648       3
2  서울본부   수색  37.58060  126.8959       1
3  서울본부   행신  37.36450  126.4952       2
4  서울본부  도라산  37.89877  126.7098       1

In [41]:
df_sub = df_subway[["역명"]]
df_sub.head()

    역명
0   서울
1   용산
2   수색
3   행신
4  도라산

In [42]:
df_sub["위도"] = df_subway['위도']
df_sub["경도"] = df_subway['경도']
df_sub.head()

C:\Users\user\AppData\Local\Temp\ipykernel_13908\3735483196.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub["위도"] = df_subway['위도']
C:\Users\user\AppData\Local\Temp\ipykernel_13908\3735483196.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub["경도"] = df_subway['경도']

    역명        위도        경도
0   서울  37.55473  126.9708
1   용산  37.52991  126.9648
2   수색  37.58060  126.8959
3   행신  37.36450  126.4952
4  도라산  37.89877  126.7098

In [43]:
df_sub.to_csv("./data/subway.csv", index=False)

In [30]:
df_busStop.head()

,정류장번호,정류장명,위도,경도,정보수집일,모바일단축번호,도시코드,도시명,관리도시명
0,ADB354000001,길안정류장,36.458658,128.891228,2024-10-28,540001.0,37040,경상북도 안동시,안동BIS
1,ADB354000002,고란.계명산휴양림입구,36.397708,128.924029,2024-10-28,540002.0,37040,경상북도 안동시,안동BIS
2,ADB354000003,금곡리,36.397504,128.926821,2024-10-28,540003.0,37040,경상북도 안동시,안동BIS
3,ADB354000004,금소리1,36.509449,128.849671,2024-10-28,540004.0,37040,경상북도 안동시,안동BIS
4,ADB354000005,금소리5,36.503629,128.854783,2024-10-28,540005.0,37040,경상북도 안동시,안동BIS

In [44]:
df_busStop = df_busStop[df_busStop["도시명"].str.contains("서울특별시", na=False, case=False)]
df_busStop

,정류장번호,정류장명,위도,경도,정보수집일,모바일단축번호,도시코드,도시명,관리도시명
53999,GGB109000013,도봉구민회관.도봉문화원(중),37.654450,127.038067,2024-10-28,10013.0,11,서울특별시,경기BIS
54000,GGB109000014,도봉구민회관.도봉문화원(중),37.654117,127.038033,2024-10-28,10014.0,11,서울특별시,경기BIS
54001,GGB109000015,쌍문역(중),37.648833,127.034750,2024-10-28,10015.0,11,서울특별시,경기BIS
54002,GGB109000016,쌍문역(중),37.648133,127.034500,2024-10-28,10016.0,11,서울특별시,경기BIS
54003,GGB109000017,우이1교앞(중),37.645150,127.032550,2024-10-28,10017.0,11,서울특별시,경기BIS
...,...,...,...,...,...,...,...,...,...
108686,GGB277103099,경복궁역(경유),37.575700,126.972583,2024-10-28,0.0,11,서울특별시,경기BIS
108689,GGB277103102,선암IC(경유),37.460383,127.020300,2024-10-28,0.0,11,서울특별시,경기BIS
108719,GGB277103135,중랑IC(경유),37.611900,127.114383,2024-10-28,0.0,11,서울특별시,경기BIS
108720,GGB277103136,중랑IC(경유),37.610817,127.114750,2024-10-28,0.0,11,서울특별시,경기BIS
108754,GGB277104766,G2001종점대기(경유),37.690317,127.045183,2024-10-28,0.0,11,서울특별시,경기BIS

In [45]:
df_bus = df_busStop[["정류장명"]]
df_bus["위도"] = df_busStop["위도"]
df_bus["경도"] = df_busStop["경도"]
df_bus.head()

C:\Users\user\AppData\Local\Temp\ipykernel_13908\837590071.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bus["위도"] = df_busStop["위도"]
C:\Users\user\AppData\Local\Temp\ipykernel_13908\837590071.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bus["경도"] = df_busStop["경도"]

                  정류장명         위도          경도
53999  도봉구민회관.도봉문화원(중)  37.654450  127.038067
54000  도봉구민회관.도봉문화원(중)  37.654117  127.038033
54001           쌍문역(중)  37.648833  127.034750
54002           쌍문역(중)  37.648133  127.034500
54003         우이1교앞(중)  37.645150  127.032550

In [46]:
df_bus.to_csv("./data/bus_stop.csv", index=False)

In [48]:
df_bus_stop = pd.read_csv("./data/서울특별시_화물자동차주선업체 목록_20210423.csv", encoding="cp949")
df_bus_stop

,면허번호,업종명,사업자구분,업체명,주사무소 우편번호,주사무소 주소,주사무소 상세주소,팩스번호,관할관청,면허상태
0,170194,화물주선업,개인,전국마린화물&이사,08216,서울특별시 구로구 구로중앙로 207,"529호(구로동, 구로동복합건물 오퍼스1)",NaN,구로구,정상
1,70164,화물주선업,법인,주식회사 카인드맨,02034,서울특별시 중랑구 공릉로2길 7,5층 2호 (묵동),NaN,중랑구,정상
2,240352,화물주선업,개인,예건물류,07562,서울특별시 강서구 공항대로 535,"10층1호(염창동,소은빌딩) (염창동)",NaN,강서구,정상
3,180220,화물주선업,법인,(주)손매니지먼트서비스,08506,서울특별시 금천구 가산디지털2로 108,312호 (가산동),NaN,금천구,정상
4,220908,화물주선업,법인,(주)상생,06752,서울특별시 서초구 바우뫼로27길 7-7,201호 (양재동),NaN,서초구,정상
...,...,...,...,...,...,...,...,...,...,...
1898,250236,화물주선업,법인,주식회사 마루흥업,05353,서울특별시 강동구 천중로42길 70,"513호 (길동, 길동청광플러스원큐브1차)",NaN,강동구,정상
1899,40155,화물주선업,법인,(주)태림로지스,04793,서울특별시 성동구 아차산로7길 15-1,3층 3103호 (성수동2가),NaN,성동구,정상
1900,170187,화물주선업,법인,(주)다가,08320,서울특별시 구로구 도림로3길 24,"3층 301호 (구로동, 구로아트빌라)",NaN,구로구,정상
1901,140168,화물주선업,법인,주식회사 밸류링크유,04165,서울특별시 마포구 마포대로 19,1005호 (마포동),NaN,마포구,정상
1902,110196,화물주선업,개인,삼성이사명가,01851,서울특별시 노원구 섬밭로 152,상가동 110호 (공릉동),NaN,노원구,정상

In [50]:
df_lh = pd.read_csv("./data/한국토지주택공사_전국 LH아파트 단지정보_20240729.csv", encoding="cp949")
df_lh

,지역본부,단지코드,단지명,세대수,동수,임대유형,주택유형,주소,준공일,입주지정시작일자,입주지정종료일자
0,강원지역본부,C02364,원주태장6단지 국민임대,464.0,4.0,건설임대,국민임대,강원특별자치도 원주시 치악로 1989(태장동원주태장LH 천년나무6단지),2020-04-01,2020-06-05,2020-07-05
1,강원지역본부,000914,강원혁신B-5블럭,424.0,6.0,건설임대,공공분양,강원특별자치도 원주시 혁신로 400(반곡동푸른숨엘에이치11단지 1101동) 400 ...,2014-10-24,2014-11-28,2014-12-31
2,강원지역본부,C02424,춘천거두2 행복주택,NaN,NaN,건설임대,분양단지,강원특별자치도 춘천시 동내면 거두택지길 70(춘천거두2지구행복주택) 행복주택,2018-02-23,2018-02-23,2018-03-25
3,강원지역본부,C02200,강릉유천 미디어촌5단지,1054.0,5.0,건설임대,국민임대+영구임대,강원특별자치도 강릉시 선수촌로 11(홍제동) 미디어촌5단지,2018-07-01,2018-11-16,2019-01-04
4,강원지역본부,C02508,춘천우두B-2블록(2단지),NaN,9.0,건설임대,공공분양,,2020-06-18,2020-09-22,2020-11-20
...,...,...,...,...,...,...,...,...,...,...,...
3192,충북지역본부,C02670,청주산단1 행복주택,552.0,3.0,건설임대,행복주택,,2024-03-28,2025-03-03,2025-05-01
3193,충북지역본부,C02699,음성맹동 행복주택,296.0,4.0,건설임대,행복주택+임대상가,충청북도 음성군 맹동면 맹동산단1길 18,2023-09-21,2023-11-30,2024-01-13
3194,충북지역본부,C02714,음성읍내 행복주택,56.0,1.0,건설임대,행복주택,충청북도 음성군 음성읍 음성천동길 172,2023-08-31,2024-01-31,2024-03-16
3195,충북지역본부,C02792,옥천삼양 행복주택,202.0,3.0,건설임대,행복주택+임대상가,충청북도 옥천군 옥천읍 삼양로3길 9-10 옥천삼양 행복주택,2024-05-30,2024-06-13,2024-07-27
3196,충북지역본부,C02891,진천문백(마을정비형),154.0,3.0,건설임대,국민임대+영구임대+행복주택,,2024-08-20,2025-03-31,2025-05-14

In [51]:
df_lh = df_lh[df_lh["지역본부"].str.contains("서울지역본부", na=False, case=False)]
df_lh

,지역본부,단지코드,단지명,세대수,동수,임대유형,주택유형,주소,준공일,입주지정시작일자,입주지정종료일자
2427,서울지역본부,000888,강남7BL,36.0,3.0,건설임대,공공분양,서울특별시 강남구 자곡동 602번지 LH 강남 아이파크,NaN,2014-10-31,2014-11-30
2428,서울지역본부,000889,강남4BL,402.0,13.0,건설임대,공공분양+토지임대부분양,서울특별시 강남구 자곡로3길 45(자곡동618),NaN,2014-11-28,2014-12-31
2429,서울지역본부,C02461,성남위례A2-15BL 지역전략산업 및 창업지원주택,473.0,4.0,건설임대,행복주택+임대상가,경기도 성남시 수정구 위례순환로 53(창곡동성남위례 LH36단지),2020-11-10,2021-01-10,2021-02-10
2430,서울지역본부,C02058,위례35단지,2568.0,14.0,건설임대,국민임대+영구임대,경기도 성남시 수정구 위례광장로 311(창곡동위례35단지) 위례 35단지,2016-06-30,2016-06-30,2016-08-27
2431,서울지역본부,C02081,남양주장현3(남양주장현5),NaN,NaN,건설임대,국민임대,경기도 남양주시 진접읍 금강로 1554-20 (휴먼시아3단지아파트),2009-08-19,2009-08-31,2009-09-29
...,...,...,...,...,...,...,...,...,...,...,...
2574,서울지역본부,C02725,서울양원 S2BL,134.0,4.0,건설임대,공공분양+행복주택,,2022-01-07,2022-01-25,2022-03-26
2575,서울지역본부,C02617,서울잠실 행복주택,40.0,1.0,건설임대,행복주택,서울특별시 송파구 백제고분로7길 8-40(잠실동),2021-12-31,2022-02-28,2022-04-13
2576,서울지역본부,C02826,성남복정1 A2블록 신혼희망타운 행복주택,129.0,7.0,건설임대,공공분양+행복주택,,2025-10-30,2025-12-31,2026-02-28
2577,서울지역본부,C02827,성남복정1 A3블록 신혼희망타운 행복주택,105.0,6.0,건설임대,공공분양+행복주택,,2025-10-30,2025-12-31,2026-02-28
2578,서울지역본부,C02832,수서역세권 A3BL 공공분양(신혼희망타운),NaN,NaN,건설임대,공공분양,,2023-06-02,2023-06-27,2023-08-25

In [53]:
df_LH = df_lh[['단지코드']]
df_LH['단지명'] = df_lh['단지명']
df_LH['주소'] = df_lh['주소']
df_LH

C:\Users\user\AppData\Local\Temp\ipykernel_13908\2425449114.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_LH['단지명'] = df_lh['단지명']
C:\Users\user\AppData\Local\Temp\ipykernel_13908\2425449114.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_LH['주소'] = df_lh['주소']

,단지코드,단지명,주소
2427,000888,강남7BL,서울특별시 강남구 자곡동 602번지 LH 강남 아이파크
2428,000889,강남4BL,서울특별시 강남구 자곡로3길 45(자곡동618)
2429,C02461,성남위례A2-15BL 지역전략산업 및 창업지원주택,경기도 성남시 수정구 위례순환로 53(창곡동성남위례 LH36단지)
2430,C02058,위례35단지,경기도 성남시 수정구 위례광장로 311(창곡동위례35단지) 위례 35단지
2431,C02081,남양주장현3(남양주장현5),경기도 남양주시 진접읍 금강로 1554-20 (휴먼시아3단지아파트)
...,...,...,...
2574,C02725,서울양원 S2BL,
2575,C02617,서울잠실 행복주택,서울특별시 송파구 백제고분로7길 8-40(잠실동)
2576,C02826,성남복정1 A2블록 신혼희망타운 행복주택,
2577,C02827,성남복정1 A3블록 신혼희망타운 행복주택,
2578,C02832,수서역세권 A3BL 공공분양(신혼희망타운),

In [54]:
len(df_LH)

152

In [ ]:
df_LH.to_csv("./data/LH.csv", index=False)