In [10]:
import pandas as pd

# 1. 데이터 불러오기
# 'apartment_data.csv'는 공공데이터포털에서 다운로드한 CSV 파일입니다.
df = pd.read_csv('./서울시 공영주차장 안내 정보.csv', encoding='cp949')  # 또는 'euc-kr'
print(df.head())

     주차장코드              주차장명                주소 주차장 종류 주차장 종류명  운영구분    운영구분명  \
0  1010089     초안산근린공원주차장(구)       도봉구 창동 24-0     NW  노외 주차장     1  시간제 주차장
1  1012254   마들스타디움(근린공원)(구)     노원구 상계동 770-2     NW  노외 주차장     1  시간제 주차장
2  1013181  마장동(건물) 공영주차장(구)     성동구 마장동 463-2     NW  노외 주차장     1  시간제 주차장
3  1025695       영등포여고 공영(구)    영등포구 신길동 184-3     NW  노외 주차장     1  시간제 주차장
4  1025696      당산근린공원 공영(구)  영등포구 당산동3가 385-0     NW  노외 주차장     1  시간제 주차장

           전화번호  주차현황 정보 제공여부                  주차현황 정보 제공여부명  ...  \
0           NaN             0                           미연계중  ...
1  02-2289-6735             0                           미연계중  ...
2  02-2204-7970             2      20~120분이내 연계데이터 존재(정보수집중)  ...
3  02-2677-1401             0                           미연계중  ...
4  02-2677-1401             1  현재~20분이내 연계데이터 존재(현재 주차대수 표현)  ...

   기본 주차 시간(분 단위) 추가 단위 요금 추가 단위 시간(분 단위) 버스 기본 주차 요금 버스 기본 주차 시간(분 단위)  \
0             NaN    300.0           10.0         0.0               0.0
1             5.0    150.0            5.0         0.0               0.0
2             5.0     50.0            5.0         0.0               0.0
3             5.0     50.0            5.0         0.0               0.0
4             5.0    150.0            5.0         0.0               0.0

   버스 추가 단위 시간(분 단위)  버스 추가 단위 요금  일 최대 요금         위도          경도
0                0.0          0.0      0.0        NaN         NaN
1                0.0          0.0  11000.0        NaN         NaN
2                0.0          0.0      NaN        NaN         NaN
3                0.0          0.0      0.0  37.515205  126.915116
4                0.0          0.0      0.0        NaN         NaN

[5 rows x 39 columns]

In [5]:
# "소재지지번주소" 열에서 "서울특별시" 또는 "경기도"가 포함된 행만 필터링
filtered_df = df[df['소재지지번주소'].str.contains('서울특별시|경기도', na=False)]

# 결과 출력
print(filtered_df)

             학교ID         학교명 학교급구분        설립일자 설립형태 본교분교구분 운영상태  \
2      B000008404       미성중학교   중학교  1984-05-17   공립     본교   운영
6      B000009682     송내중앙중학교   중학교  2008-10-10   공립     본교   운영
13     B000024686      청목초등학교  초등학교  2015-06-30   공립     본교   운영
22     B000008246       장충중학교   중학교  1947-08-25   사립     본교   운영
31     B000012494      범박고등학교  고등학교  2006-03-01   공립     본교   운영
...           ...         ...   ...         ...  ...    ...  ...
11968  B000002175    서울고일초등학교  초등학교  1984-05-06   공립     본교   운영
11976  B000030308   운정해오름초등학교  초등학교  2024-09-01   공립     본교   운영
11977  B000030715     내리숲초등학교  초등학교  2024-09-01   공립     본교   운영
11978  B000011492  부천정보산업고등학교  고등학교  1993-02-04   공립     본교   운영
11987  B000030436      새봄초등학교  초등학교  2021-03-01   공립     본교   운영

                      소재지지번주소                소재지도로명주소  시도교육청코드    시도교육청명  \
2        서울특별시 관악구 신림동 745-24     서울특별시 관악구 문성로16길 40  7010000  서울특별시교육청
6            경기도 동두천시 송내동 665         경기도 동두천시 중앙로 78  7530000    경기도교육청
13            경기도 화성시 청계동 539    경기도 화성시 동탄순환대로21길 10  7530000    경기도교육청
22       서울특별시 중구 신당동 432-460      서울특별시 중구 동호로15길 93  7010000  서울특별시교육청
31     경기도 부천시 소사구 범박동 113-70    경기도 부천시 소사구 범박로 27-1  7530000    경기도교육청
...                       ...                     ...      ...       ...
11968       서울특별시 강동구 상일동 125    서울특별시 강동구 구천면로93길 20  7010000  서울특별시교육청
11976        경기도 파주시 다율동 1024        경기도 파주시 범벅들길 155  7530000    경기도교육청
11977    경기도 화성시 봉담읍 내리 557-1  경기도 화성시 봉담읍 삼봉안1길 21-7  7530000    경기도교육청
11978      경기도 부천시 원미구 상동 391      경기도 부천시 원미구 신상로 94  7530000    경기도교육청
11987     경기도 화성시 병점동 756-298        경기도 화성시 병점노을로 19  7530000    경기도교육청

       교육지원청코드          교육지원청명        생성일자        변경일자         위도          경도  \
2      7132000  서울특별시동작관악교육지원청  2013-11-29  2024-07-09  37.475383  126.912089
6      7602000   경기도동두천양주교육지원청  2013-11-29  2024-07-09  37.888421  127.052620
13     7679000    경기도화성오산교육지원청  2013-11-29  2024-07-09  37.195771  127.117431
22     7061000    서울특별시중부교육지원청  2013-11-29  2024-07-09  37.553515  127.006415
31     7581000      경기도부천교육지원청  2013-11-29  2024-07-09  37.467683  126.811738
...        ...             ...         ...         ...        ...         ...
11968  7130000  서울특별시강동송파교육지원청  2013-11-29  2024-07-09  37.551543  127.169410
11976  7681000      경기도파주교육지원청  2013-11-29  2024-08-30  37.741757  126.730648
11977  7679000    경기도화성오산교육지원청  2013-11-29  2024-08-30  37.226172  126.923735
11978  7581000      경기도부천교육지원청  2013-11-29  2024-07-09  37.496365  126.749410
11987  7679000    경기도화성오산교육지원청  2013-11-29  2024-07-09  37.201463  127.029773

          데이터기준일자   제공기관코드             제공기관명
2      2024-09-20  B555223  재단법인한국지방교육행정연구재단
6      2024-09-20  B555223  재단법인한국지방교육행정연구재단
13     2024-09-20  B555223  재단법인한국지방교육행정연구재단
22     2024-09-20  B555223  재단법인한국지방교육행정연구재단
31     2024-09-20  B555223  재단법인한국지방교육행정연구재단
...           ...      ...               ...
11968  2024-09-20  B555223  재단법인한국지방교육행정연구재단
11976  2024-09-20  B555223  재단법인한국지방교육행정연구재단
11977  2024-09-20  B555223  재단법인한국지방교육행정연구재단
11978  2024-09-20  B555223  재단법인한국지방교육행정연구재단
11987  2024-09-20  B555223  재단법인한국지방교육행정연구재단

[3829 rows x 20 columns]

In [9]:
# 필요한 컬럼만 선택
selected_columns = ['학교명', '위도', '경도', '설립형태', '소재지도로명주소']
filtered_selected_df = filtered_df[selected_columns]

# 결과 확인
print(filtered_selected_df)

# 필터링된 데이터를 새로운 CSV 파일로 저장
filtered_selected_df.to_csv('초등학교_전처리.csv', index=False, encoding='utf-8-sig')

              학교명         위도          경도 설립형태                소재지도로명주소
2           미성중학교  37.475383  126.912089   공립     서울특별시 관악구 문성로16길 40
6         송내중앙중학교  37.888421  127.052620   공립         경기도 동두천시 중앙로 78
13         청목초등학교  37.195771  127.117431   공립    경기도 화성시 동탄순환대로21길 10
22          장충중학교  37.553515  127.006415   사립      서울특별시 중구 동호로15길 93
31         범박고등학교  37.467683  126.811738   공립    경기도 부천시 소사구 범박로 27-1
...           ...        ...         ...  ...                     ...
11968    서울고일초등학교  37.551543  127.169410   공립    서울특별시 강동구 구천면로93길 20
11976   운정해오름초등학교  37.741757  126.730648   공립        경기도 파주시 범벅들길 155
11977     내리숲초등학교  37.226172  126.923735   공립  경기도 화성시 봉담읍 삼봉안1길 21-7
11978  부천정보산업고등학교  37.496365  126.749410   공립      경기도 부천시 원미구 신상로 94
11987      새봄초등학교  37.201463  127.029773   공립        경기도 화성시 병점노을로 19

[3829 rows x 5 columns]

In [14]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./서울시 공영주차장 안내 정보.csv', encoding='cp949')  # 파일 경로와 인코딩 확인

# 필요한 컬럼만 선택 (금액 정보 포함)
selected_columns = [
    '주차장명', '위도', '경도', '주소', '전화번호', '유무료구분', 
    '기본 주차 요금', '추가 단위 요금', '기본 주차 시간(분 단위)', '추가 단위 시간(분 단위)',
    '일 최대 요금', '버스 기본 주차 요금', '버스 추가 단위 요금'
]
processed_df = df[selected_columns]

# 결과 확인
print(processed_df.head())

# 전처리된 데이터 저장
processed_df.to_csv('서울시 공영주차장_전처리.csv', index=False, encoding='utf-8-sig')

               주차장명         위도          경도                주소          전화번호  \
0     초안산근린공원주차장(구)        NaN         NaN       도봉구 창동 24-0           NaN
1   마들스타디움(근린공원)(구)        NaN         NaN     노원구 상계동 770-2  02-2289-6735
2  마장동(건물) 공영주차장(구)        NaN         NaN     성동구 마장동 463-2  02-2204-7970
3       영등포여고 공영(구)  37.515205  126.915116    영등포구 신길동 184-3  02-2677-1401
4      당산근린공원 공영(구)        NaN         NaN  영등포구 당산동3가 385-0  02-2677-1401

  유무료구분  기본 주차 요금  추가 단위 요금  기본 주차 시간(분 단위)  추가 단위 시간(분 단위)  일 최대 요금  \
0     Y       0.0     300.0             NaN            10.0      0.0
1     Y     150.0     150.0             5.0             5.0  11000.0
2     Y      50.0      50.0             5.0             5.0      NaN
3     Y      50.0      50.0             5.0             5.0      0.0
4     Y     150.0     150.0             5.0             5.0      0.0

   버스 기본 주차 요금  버스 추가 단위 요금
0          0.0          0.0
1          0.0          0.0
2          0.0          0.0
3          0.0          0.0
4          0.0          0.0

In [15]:
import pandas as pd

# 1. 데이터 불러오기
# 'apartment_data.csv'는 공공데이터포털에서 다운로드한 CSV 파일입니다.
df = pd.read_csv('./서울시 주요 공원현황.csv', encoding='cp949')  # 또는 'euc-kr'
print(df.head())

   연번     공원명                                               공원개요  \
0   1    남산공원  남산공원은 도심에 위치하여 서울시민에게 맑은 공기를 제공하는 자연휴식처이며 산책 꽃...
1   2  길동생태공원  길동생태공원은 생물의 서식처를 제공하고 종다양성을 증진시키며 자연생태계의 생물들을 ...
2   3   서울대공원  서울대공원은 세계 각국의 야생동물들이 살아 숨 쉬는 서울동물원과 다양한 재미와 즐거...
3   4     서울숲  서울숲은 한강과 중랑천이 만나고 한강-용산-남찬-청계천-서울숲-한강으로 연결되는 서...
4   5   월드컵공원  월드컵공원은 서울의 서쪽에 위치하여 1978년부터 1993년까지 15년간 서울시민이...

                                             면적        개원일  \
0  2896887㎡ 임 야 : 2454140㎡ 녹지대 및 기타시설 : 442747㎡  1968.9.10
1                                      79258.7㎡  1999.5.20
2                                     9132690m²   1984.5.1
3                                       480994㎡  2005.6.18
4                                      2284085㎡   2002.5.1

                                                주요시설  \
0  기반시설 : 광장 45950㎡ 도로 108530㎡ 산책로 6.7㎞ (북측:3.7㎞/...
1             생태문화센터, 탐방객안내센터, 반딧불이 체험관, 목재데크, 조류관찰대
2  동물원 식물원 테마가든(장미원 어린이동물원 피크닉장) 치유숲 산림욕장 캠핑장 국립현...
3  문화예술시설: 바닥분수 거울연못 군마상 야외무대 가족마당무대 생태시설: 꽃사슴방사장...
4  평화의 공원 월드컵공원전시관(879㎡) 유니세프광장(2400㎡) 평화광장(5217㎡...

                                                주요식물  \
0                  소나무 단풍 아카시아 상수리나무 등 191종 2881870주
1          소나무 보리수 등 64종 31800주 산국 부들 등 138종 192800본
2                      엘레강스야자, 용설란, 파리지옥, 네펜데스, 장미 등
3  수 목 : 소나무 섬잣나무 계수나무 외 95종 415795주 식물원 : 선인장 등 ...
4                                                NaN

                                                 안내도  \
0  http://parks.seoul.go.kr/upload/seditorMulti/2...
1  http://parks.seoul.go.kr/template/common/img/p...
2  https://grandpark.seoul.go.kr/conts/contsView/...
3  http://parks.seoul.go.kr/template/common/img/p...
4  http://parks.seoul.go.kr/template/common/img/p...

                                                오시는길  \
0  명동역(남산케이블카 와룡묘 서울애니메이션센터 방면) 도보 명동역 3번출구 → 퍼시픽...
1  지하철: 9호선 중앙보훈병원역 3번출구에서 시내버스 환승 5호선 강동역 4번출구에서...
2  지하철 4호선 대공원역 하차(2번 출구) 도보 15분 정도 문의처 02)500-73...
3                                                NaN
4  지하철 6호선 월드컵경기장역 하차 → 1번 출구로 나온 후 직진 → 큰길(도로)이 ...

                                             이용시참고사항  \
0  남산공원 차량통행 금지안내 2005년 5월 1일부터 남산공원에 일반승용차 택시 통행...
1  매주 월요일은 휴관입니다 사전예약 후 입장하실 수 있습니다. 공원을 깨끗하게 이용합...
2  일반사항 공원을 깨끗하게 이용합니다. 대중교통을 이용해 주세요. 기념물 시설물 풀과...
3  지하철: 분당선 서울숲역 4번출구에서 도보 약 2분 2호선 뚝섬역 8번출구에서 도보...
4  일반사항 공원을 깨끗하게 이용합니다. 대중교통을 이용해 주세요. 기념물 시설물 풀과...

                                                 이미지   지역  \
0  http://parks.seoul.go.kr/file/info/view.do?fId...   중구
1  http://parks.seoul.go.kr/file/info/view.do?fId...  강동구
2  http://parks.seoul.go.kr/file/info/view.do?fId...  과천시
3  http://parks.seoul.go.kr/file/info/view.do?fId...  성동구
4  http://parks.seoul.go.kr/file/info/view.do?fId...  마포구

                           공원주소              관리부서                     전화번호  \
0        서울특별시 중구 삼일대로 231(예장동)          중부공원여가센터             02-3783-5900
1  서울특별시 강동구 천호대로 1291(길동생태공원)     동부공원여가센터 공원운영과  02-472-2770/02-489-2770
2            경기도 과천시 대공원광장로 102             전략기획실              02-500-7032
3    서울특별시 성동구 뚝섬로 273 (성수동1가)   동부여가센터 서울숲 관리사무소             02-460-2905
4     서울특별시 마포구 하늘공원로 84(월드컵공원)          서부공원여가센터              02-300-5501

   X좌표(GRS80TM)  Y좌표(GRS80TM)  X좌표(WGS84)  Y좌표(WGS84)  \
0    198364.107    450395.554  126.990377   37.550140
1    213554.120    448852.675  127.154779   37.540394
2    200994.267    437163.981  127.019846   37.426449
3    203695.432    449290.726  127.041798   37.543072
4    190658.070    451598.831  126.878907   37.571805

                                                바로가기
0    http://parks.seoul.go.kr/template/sub/namsan.do
1   http://parks.seoul.go.kr/template/sub/gildong.do
2                      http://grandpark.seoul.go.kr/
3  http://parks.seoul.go.kr/template/sub/seoulfor...
4  http://parks.seoul.go.kr/template/sub/worldcup...

In [18]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./서울시 주요 공원현황.csv', encoding='cp949')  # 파일 경로와 인코딩 확인

# 필요한 컬럼만 선택
selected_columns = ['공원명', 'Y좌표(WGS84)', 'X좌표(WGS84)', '이미지', '지역', '공원주소']
processed_df = df[selected_columns]

# 결과 확인
print(processed_df.head())

# 전처리된 데이터를 CSV 파일로 저장
processed_df.to_csv('서울시 주요 공원_전처리', index=False, encoding='utf-8-sig')

      공원명  Y좌표(WGS84)  X좌표(WGS84)  \
0    남산공원   37.550140  126.990377
1  길동생태공원   37.540394  127.154779
2   서울대공원   37.426449  127.019846
3     서울숲   37.543072  127.041798
4   월드컵공원   37.571805  126.878907

                                                 이미지   지역  \
0  http://parks.seoul.go.kr/file/info/view.do?fId...   중구
1  http://parks.seoul.go.kr/file/info/view.do?fId...  강동구
2  http://parks.seoul.go.kr/file/info/view.do?fId...  과천시
3  http://parks.seoul.go.kr/file/info/view.do?fId...  성동구
4  http://parks.seoul.go.kr/file/info/view.do?fId...  마포구

                           공원주소
0        서울특별시 중구 삼일대로 231(예장동)
1  서울특별시 강동구 천호대로 1291(길동생태공원)
2            경기도 과천시 대공원광장로 102
3    서울특별시 성동구 뚝섬로 273 (성수동1가)
4     서울특별시 마포구 하늘공원로 84(월드컵공원)

In [19]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./서울주택도시공사_공공주택_현황_위경도추가_쉼표.csv', encoding='cp949')  # 파일 경로와 인코딩 확인

df.head()

,자치구,단지명,임대유형,주소,전체 세대수,임대 세대수,사용승인일,주소_정제,위도,경도
0,노원구,하계5단지,영구임대,섬밭로 201 하계동 시영아파트,640,640,1989-11-10,서울특별시 섬밭로 201 하계동 시영아파트,37.633880,127.065914
1,마포구,성산,영구임대,월드컵로 207 성산동 도시개발공사성산아파트,1807,1807,1991-05-31,서울특별시 월드컵로 207 성산동 도시개발공사성산아파트,37.564657,126.901751
2,중랑구,면목,영구임대,용마산로 228 면목동 도시개발아파트,905,905,1991-09-30,서울특별시 용마산로 228 면목동 도시개발아파트,37.574166,127.088302
3,노원구,중계4단지,공공임대,노원로19길 31 중계동 목화아파트,1979,1979,1991-11-30,서울특별시 노원로19길 31 중계동 목화아파트,37.643488,127.068759
4,노원구,중계3단지,영구임대,노원로 331 중계동 시영3단지목련아파트,2619,2619,1991-11-30,서울특별시 노원로 331 중계동 시영3단지목련아파트,37.646171,127.069521

In [21]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./서울시 공영주차장_전처리.csv', encoding='utf-8-sig')  # 파일 경로와 인코딩 확인

df.head()

,주차장명,위도,경도,주소,전화번호,유무료구분,기본 주차 요금,추가 단위 요금,기본 주차 시간(분 단위),추가 단위 시간(분 단위),일 최대 요금,버스 기본 주차 요금,버스 추가 단위 요금
0,초안산근린공원주차장(구),NaN,NaN,도봉구 창동 24-0,NaN,Y,0.0,300.0,NaN,10.0,0.0,0.0,0.0
1,마들스타디움(근린공원)(구),NaN,NaN,노원구 상계동 770-2,02-2289-6735,Y,150.0,150.0,5.0,5.0,11000.0,0.0,0.0
2,마장동(건물) 공영주차장(구),NaN,NaN,성동구 마장동 463-2,02-2204-7970,Y,50.0,50.0,5.0,5.0,NaN,0.0,0.0
3,영등포여고 공영(구),37.515205,126.915116,영등포구 신길동 184-3,02-2677-1401,Y,50.0,50.0,5.0,5.0,0.0,0.0,0.0
4,당산근린공원 공영(구),NaN,NaN,영등포구 당산동3가 385-0,02-2677-1401,Y,150.0,150.0,5.0,5.0,0.0,0.0,0.0

In [24]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./서울시 주요 공원_전처리', encoding='utf-8-sig')  # 파일 경로와 인코딩 확인

df.head()

,공원명,Y좌표(WGS84),X좌표(WGS84),이미지,지역,공원주소
0,남산공원,37.550140,126.990377,http://parks.seoul.go.kr/file/info/view.do?fId...,중구,서울특별시 중구 삼일대로 231(예장동)
1,길동생태공원,37.540394,127.154779,http://parks.seoul.go.kr/file/info/view.do?fId...,강동구,서울특별시 강동구 천호대로 1291(길동생태공원)
2,서울대공원,37.426449,127.019846,http://parks.seoul.go.kr/file/info/view.do?fId...,과천시,경기도 과천시 대공원광장로 102
3,서울숲,37.543072,127.041798,http://parks.seoul.go.kr/file/info/view.do?fId...,성동구,서울특별시 성동구 뚝섬로 273 (성수동1가)
4,월드컵공원,37.571805,126.878907,http://parks.seoul.go.kr/file/info/view.do?fId...,마포구,서울특별시 마포구 하늘공원로 84(월드컵공원)

In [25]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./서울시 주요 공원_전처리', encoding='utf-8-sig')

# 열 이름 변경
df.rename(columns={'Y좌표(WGS84)': '위도', 'X좌표(WGS84)': '경도'}, inplace=True)

# 결과 저장
df.to_csv('./서울시_주요_공원_위경도전처리리.csv', index=False, encoding='utf-8-sig')

print("Y좌표(WGS84)는 위도로, X좌표(WGS84)는 경도로 변경 후 저장되었습니다.")

Y좌표(WGS84)는 위도로, X좌표(WGS84)는 경도로 변경 후 저장되었습니다.

In [27]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./서울교통공사_1_8호선 역사 좌표(위경도) 정보_20241031.csv', encoding='cp949')  # 파일 경로와 인코딩 확인

df.head()

   연번  호선  고유역번호(외부역코드)    역명         위도          경도        작성일자
0   1   1           150    서울  37.553150  126.972533  1974-02-28
1   2   1           151    시청  37.563590  126.975407  1974-08-15
2   3   1           152    종각  37.570203  126.983116  1974-08-15
3   4   1           153  종로3가  37.570429  126.992095  1974-08-15
4   5   1           154  종로5가  37.570971  127.001900  1974-03-31

In [28]:
# 필요한 열만 선택
filtered_df = df[['역명', '위도', '경도']]

# 결과 확인
print(filtered_df.head())

     역명         위도          경도
0    서울  37.553150  126.972533
1    시청  37.563590  126.975407
2    종각  37.570203  126.983116
3  종로3가  37.570429  126.992095
4  종로5가  37.570971  127.001900

In [30]:
# 필요한 열만 선택
filtered_df2 = df[['역명', '위도', '경도']]

# 결과 확인
print(filtered_df2.head())

     역명         위도          경도
0    개화  37.578608  126.798153
1  김포공항  37.562434  126.801058
2  공항시장  37.563726  126.810678
3   신방화  37.567532  126.816601
4  마곡나루  37.567336  126.829497

In [33]:
import pandas as pd

# 두 데이터프레임 병합
merged_df = pd.concat([filtered_df, filtered_df2], ignore_index=True)

merged_df.head()

# CSV 파일로 저장
merged_df.to_csv('지하철_전처리.csv', index=False, encoding='utf-8-sig')

print("병합된 데이터가 'merged_stations.csv'로 저장되었습니다.")

병합된 데이터가 'merged_stations.csv'로 저장되었습니다.

In [35]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./지하철_전처리.csv', encoding='utf-8-sig')  # 파일 경로와 인코딩 확인

df.head()

     역명         위도          경도
0    서울  37.553150  126.972533
1    시청  37.563590  126.975407
2    종각  37.570203  126.983116
3  종로3가  37.570429  126.992095
4  종로5가  37.570971  127.001900

In [36]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./지하철_전처리.csv', encoding='utf-8-sig')

# 중복 제거
df = df.drop_duplicates()

# 위도와 경도 중 하나라도 값이 없는 행 제거
df = df.dropna(subset=['위도', '경도'])

# 결과를 CSV로 저장
df.to_csv('지하철_전처리_최종.csv', index=False, encoding='utf-8-sig')

print("중복 제거 및 결측값 처리 후 데이터가 'cleaned_subway_stations.csv'로 저장되었습니다.")

중복 제거 및 결측값 처리 후 데이터가 'cleaned_subway_stations.csv'로 저장되었습니다.

In [76]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./서울시 공동주택 아파트 정보.csv', encoding='cp949')  # 파일 경로와 인코딩 확인

df.head()
data = df[df['k-세대타입(분양형태)'] == '임대']
data

data.to_csv('서울 공동주택 임대만.csv', index=False, encoding='utf-8-sig')

In [ ]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./서울시 공동주택 아파트 정보.csv', encoding='cp949')  # 파일 경로와 인코딩 확인

df.head()
# 공공분양 키워드 필터링
public_sale_keywords = ['공공분양', '국민주택', '행복주택']
df['is_public_sale'] = df['k-아파트명'].apply(lambda x: any(keyword in x for keyword in public_sale_keywords))

# 공공분양 주택 필터링
public_sales = df[df['is_public_sale'] == True]

# 결과 확인
print("공공분양 데이터")
public_sales

공공분양 데이터

Series([], Name: count, dtype: int64)

In [53]:
df.columns

Index(['번호', 'k-아파트코드', 'k-아파트명', 'k-단지분류(아파트,주상복합등등)', 'kapt도로명주소',
       '주소(시도)k-apt주소split', '주소(시군구)', '주소(읍면동)', '나머지주소', '주소(도로명)',
       '주소(도로상세주소)', 'k-전화번호', 'k-팩스번호', '단지소개기존clob', '단지첨부파일',
       'k-세대타입(분양형태)', 'k-관리방식', 'k-복도유형', 'k-난방방식', 'k-전체동수', 'k-전체세대수',
       'k-건설사(시공사)', 'k-시행사', 'k-사용검사일-사용승인일', 'k-연면적', 'k-주거전용면적',
       'k-관리비부과면적', 'k-전용면적별세대현황(60㎡이하)', 'k-전용면적별세대현황(60㎡~85㎡이하)',
       'k-85㎡~135㎡이하', 'k-135㎡초과', 'k-홈페이지', 'k-등록일자', 'k-수정일자', '고용보험관리번호',
       '경비비관리형태', '세대전기계약방법', '청소비관리형태', '건축면적', '주차대수', '기타/의무/임대/임의=1/2/3/4',
       '단지승인일', '사용허가여부', '관리비 업로드', '좌표X', '좌표Y', '단지신청일', 'is_public_sale'],
      dtype='object')

In [54]:
# 공공분양 키워드 정의
public_sale_keywords = ['공공분양', '국민주택', '행복주택']

# 'k-아파트명'에 키워드가 포함된 데이터 필터링
filtered_df = df[df['k-아파트명'].str.contains('|'.join(public_sale_keywords), na=False)]

# 결과 확인
print(filtered_df)

         번호    k-아파트코드           k-아파트명 k-단지분류(아파트,주상복합등등)  \
2361  17821  A10027157         서울가좌행복주택                아파트
2427  19956  A10026434      서울 오류동 행복주택                아파트
2479  20981  A10025677          은뜨락행복주택                아파트
2662  40194  A10024244         서울휘경행복주택                아파트
2663  40195  A10024237  청신호 행복주택 정릉하늘마루     도시형 생활주택(연립주택)
2768  40355  A10023118    공덕동 크로시티 행복주택                아파트

                   kapt도로명주소 주소(시도)k-apt주소split 주소(시군구) 주소(읍면동)   나머지주소  \
2361        서울특별시 마포구 성암로 28                 서울     마포구     성산동     NaN
2427    서울특별시 구로구 경인로20가길 68                 서울     구로구     오류동     NaN
2479       서울특별시 은평구 통일로 972                 서울     은평구     진관동  은뜨락아파트
2662    서울특별시 동대문구 장안벚꽃로 317                 서울    동대문구     휘경동     NaN
2663  서울특별시 성북구 정릉로10가길 6-31                 서울     성북구     정릉동     NaN
2768     서울특별시 마포구 백범로31길 19                 서울     마포구     공덕동     NaN

      주소(도로명)  ...     건축면적   주차대수 기타/의무/임대/임의=1/2/3/4                  단지승인일  \
2361      성암로  ...     0.00    0.0                  임대                    NaN
2427  경인로20가길  ...     0.00    0.0                  임대                    NaN
2479      통일로  ...  2235.85  260.0                  임대  2019-03-12 16:40:52.0
2662    장안벚꽃로  ...      NaN    NaN                  임대                    NaN
2663  정릉로10가길  ...      NaN    NaN                  임대                    NaN
2768   백범로31길  ...  1581.16  160.0                  임대  2023-07-19 14:13:36.0

     사용허가여부 관리비 업로드            좌표X        좌표Y                  단지신청일  \
2361      Y       N  126.913252206  37.569150  2017-03-03 02:15:49.0
2427      Y       N  126.846646709  37.495585  2018-05-09 05:58:39.0
2479      Y       N  126.919916212  37.630176  2019-03-08 02:23:01.0
2662      Y       N            NaN        NaN                    NaN
2663      Y       N            NaN        NaN                    NaN
2768      Y       N    126.9497275  37.546677  2023-07-19 13:40:52.0

      is_public_sale
2361            True
2427            True
2479            True
2662            True
2663            True
2768            True

[6 rows x 48 columns]

In [70]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./한국토지주택공사_전국 LH아파트 단지정보_20240729.csv', encoding='cp949')  # 파일 경로와 인코딩 확인

df

data = df[df['지역본부'] == '서울지역본부']
data['주택유형'].value_counts()

주택유형
공공분양                       45
공공임대(5년)                   19
영구임대+임대상가                  15
공공분양+공공임대(5년)              11
행복주택                        8
공공임대(10년)                   7
국민임대                        6
공공분양+행복주택                   6
공공분양+공공임대(10년)              5
공공임대(50년)                   5
행복주택+임대상가                   5
분양단지                        4
영구임대                        2
국민임대+영구임대                   2
외인임대                        2
공공분양+공공임대(10년)+공공임대(분납)     2
공공분양+토지임대부분양                1
공공임대(5년)+공공임대(10년)+국민임대     1
공공분양+공공임대(50년)              1
국민임대+영구임대+행복주택+임대상가         1
장기전세+국민임대+영구임대              1
장기전세                        1
임대상가+아파트형공장(임대)             1
영구임대+행복주택                   1
Name: count, dtype: int64

In [71]:
data.to_csv('서울 LH만 남김김.csv', index=False, encoding='utf-8-sig')

In [77]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./서울시 공동주택 아파트 정보.csv', encoding='cp949')  # 파일 경로와 인코딩 확인

df.head()
data1 = df[df['k-세대타입(분양형태)'] == '임대']
data1

import pandas as pd

# 데이터 불러오기
df2 = pd.read_csv('./한국토지주택공사_전국 LH아파트 단지정보_20240729.csv', encoding='cp949')  # 파일 경로와 인코딩 확인

df2

data2 = df2[df2['지역본부'] == '서울지역본부']

In [78]:
data1.head()

,번호,k-아파트코드,k-아파트명,"k-단지분류(아파트,주상복합등등)",kapt도로명주소,주소(시도)k-apt주소split,주소(시군구),주소(읍면동),나머지주소,주소(도로명),...,청소비관리형태,건축면적,주차대수,기타/의무/임대/임의=1/2/3/4,단지승인일,사용허가여부,관리비 업로드,좌표X,좌표Y,단지신청일
2,3,A13873701,오금현대백조(임대),아파트,서울특별시 송파구 양재대로72길 20,서울,송파구,오금동,20-2,양재대로72길,...,위탁,6892.79,60.0,임의,2013-11-21 16:43:07.0,Y,N,127.1287745,37.508906,2013-03-07 09:46:59.0
125,129,A13983101,상계마들,아파트,서울특별시 노원구 덕릉로70가길 101,서울,노원구,상계동,상계마들아파트,덕릉로70가길,...,위탁,2051.74,51.0,임대,2015-12-18 14:37:18.0,Y,N,127.0569566,37.641693,2013-03-07 09:46:22.0
166,172,A14207201,래미안수유임대,아파트,서울특별시 강북구 한천로159길 8,서울,강북구,수유동,래미안수유(임대),한천로159길,...,위탁,8023.00,126.0,임대,2019-03-18 10:27:24.0,Y,N,127.0181926,37.644796,2013-03-07 09:46:34.0
298,306,A13981001,상계불암대림제2,아파트,서울특별시 노원구 덕릉로94가길 41,서울,노원구,상계동,1290,덕릉로94가길,...,위탁,0.00,0.0,임대,2013-06-23 12:40:30.0,Y,N,127.0779474,37.663907,2013-03-07 09:46:40.0
311,319,A13613002,월곡2SHville임대,아파트,서울특별시 성북구 회기로5길 142,서울,성북구,하월곡동,226-1,회기로5길,...,위탁,0.00,148.0,임대,2013-06-23 13:00:15.0,Y,N,127.0417743,37.597555,2013-03-07 09:46:33.0

In [79]:
data2.head()

,지역본부,단지코드,단지명,세대수,동수,임대유형,주택유형,주소,준공일,입주지정시작일자,입주지정종료일자
2427,서울지역본부,888,강남7BL,36.0,3.0,건설임대,공공분양,서울특별시 강남구 자곡동 602번지 LH 강남 아이파크,NaN,2014-10-31,2014-11-30
2428,서울지역본부,889,강남4BL,402.0,13.0,건설임대,공공분양+토지임대부분양,서울특별시 강남구 자곡로3길 45(자곡동618),NaN,2014-11-28,2014-12-31
2429,서울지역본부,C02461,성남위례A2-15BL 지역전략산업 및 창업지원주택,473.0,4.0,건설임대,행복주택+임대상가,경기도 성남시 수정구 위례순환로 53(창곡동성남위례 LH36단지),2020-11-10,2021-01-10,2021-02-10
2430,서울지역본부,C02058,위례35단지,2568.0,14.0,건설임대,국민임대+영구임대,경기도 성남시 수정구 위례광장로 311(창곡동위례35단지) 위례 35단지,2016-06-30,2016-06-30,2016-08-27
2431,서울지역본부,C02081,남양주장현3(남양주장현5),NaN,NaN,건설임대,국민임대,경기도 남양주시 진접읍 금강로 1554-20 (휴먼시아3단지아파트),2009-08-19,2009-08-31,2009-09-29

In [1]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./마이홈_merged_with_geo.csv', encoding='utf-8-sig')  # 파일 경로와 인코딩 확인
df.head()

,공급번호,공급면적(전용),공급면적(공용),임대보증금(원),월 임대료(원),전환보증금(원),단지명,주소,주택유형,세대수,임대사업자,주차대수,img,위도,경도
0,45.0,45.73㎡,3.06㎡,"4,951,000","338,610",0,서울특별시 강남구,서울특별시 강남구 논현로117길 12-4,다가구주택,7,LH서울,0,https://www.myhome.go.kr/jfile/preview.do?file...,37.509894,127.031402
1,46.0,46.89㎡,3.14㎡,"5,104,000","343,230",0,서울특별시 강남구,서울특별시 강남구 논현로117길 12-4,다가구주택,7,LH서울,0,https://www.myhome.go.kr/jfile/preview.do?file...,37.509894,127.031402
2,49.0,49.88㎡,3.34㎡,"3,606,000","199,330",0,서울특별시 강남구,서울특별시 강남구 논현로117길 12-4,다가구주택,7,LH서울,0,https://www.myhome.go.kr/jfile/preview.do?file...,37.509894,127.031402
3,49.0,49.93㎡,3.34㎡,"5,467,000","384,330",0,서울특별시 강남구,서울특별시 강남구 논현로117길 12-4,다가구주택,7,LH서울,0,https://www.myhome.go.kr/jfile/preview.do?file...,37.509894,127.031402
4,51.0,51.62㎡,3.46㎡,"3,742,000","206,230",0,서울특별시 강남구,서울특별시 강남구 논현로117길 12-4,다가구주택,7,LH서울,0,https://www.myhome.go.kr/jfile/preview.do?file...,37.509894,127.031402

In [2]:
# 구 이름 리스트
gu_list = [
    '강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구',
    '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구',
    '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'
]

# '단지명'에 '서울특별시'와 구 이름이 포함된 경우 수정
df['단지명'] = df.apply(
    lambda row: row['주소'].replace('서울특별시', '').strip() 
    if any(f"서울특별시 {gu}" in row['단지명'] for gu in gu_list) else row['단지명'], 
    axis=1
)

# 결과 확인
print(df[['단지명', '주소']].head())

df.to_csv('마이홈_mergefinal_단지명 변환.csv', index=False, encoding='utf-8-sig')

                단지명                      주소
0  강남구 논현로117길 12-4  서울특별시 강남구 논현로117길 12-4
1  강남구 논현로117길 12-4  서울특별시 강남구 논현로117길 12-4
2  강남구 논현로117길 12-4  서울특별시 강남구 논현로117길 12-4
3  강남구 논현로117길 12-4  서울특별시 강남구 논현로117길 12-4
4  강남구 논현로117길 12-4  서울특별시 강남구 논현로117길 12-4

In [1]:
import pandas as pd

# CSV 파일 로드
file_path = 'C:/Lecture/final/hospital.csv'
df = pd.read_csv(file_path, encoding='cp949')
df.columns

Index(['기관ID', '주소', '병원분류', '병원분류명', '응급의료기관코드', '응급의료기관코드명', '응급실운영여부(1/2)',
       '비고', '기관설명상세', '간이약도', '기관명', '대표전화1', '응급실전화', '진료시간(월요일)C',
       '진료시간(화요일)C', '진료시간(수요일)C', '진료시간(목요일)C', '진료시간(금요일)C', '진료시간(토요일)C',
       '진료시간(일요일)C', '진료시간(공휴일)C', '진료시간(월요일)S', '진료시간(화요일)S', '진료시간(수요일)S',
       '진료시간(목요일)S', '진료시간(금요일)S', '진료시간(토요일)S', '진료시간(일요일)S', '진료시간(공휴일)S',
       '우편번호1', '우편번호2', '병원경도', '병원위도', '작업시간'],
      dtype='object')

In [2]:
import pandas as pd

# CSV 파일 로드
file_path = 'C:/Lecture/final/hospital.csv'
df = pd.read_csv(file_path, encoding='cp949')

df = df[['기관명', '병원위도', '병원경도','주소','대표전화1','진료시간(토요일)S','진료시간(월요일)C']]

# "한의원" 또는 "성형"이 포함된 행 제거
df_filtered = df[~df['기관명'].str.contains('한의원|성형|피부', na=False)]

df_filtered.head()

,기관명,병원위도,병원경도,주소,대표전화1,진료시간(토요일)S,진료시간(월요일)C
0,가산기대찬의원,37.480394,126.884122,"서울특별시 금천구 벚꽃로 286, 삼성리더스타워 111~114호 (가산동)",02-6267-2580,900.0,1930
1,365엠씨의원,37.516604,127.021809,"서울특별시 강남구 도산대로 118 (논현동, 신사빌딩 2층)",02-516-3650,1100.0,2000
2,(의)가산의료재단광동병원,37.514281,127.062147,서울특별시 강남구 봉은사로 612 (삼성동),02-2222-4888,900.0,1800
3,000의원,37.507645,127.022492,"서울특별시 서초구 강남대로 509, 하늘안과 B동 7층 (반포동)",02-6241-0001,1000.0,2000
4,가로수치과의원,37.481918,126.929377,"서울특별시 관악구 신원로 38, 5층 (신림동, 청암빌딩)",02-882-2750,1000.0,1900

In [4]:
import pandas as pd
import cx_Oracle

# CSV 파일 로드
file_path = './hospital.csv'
df = pd.read_csv(file_path, encoding='cp949')

df.value_counts()

기관ID      주소                                            병원분류  병원분류명  응급의료기관코드  응급의료기관코드명  응급실운영여부(1/2)  비고                                            기관설명상세                                                                                                                                           간이약도                  기관명            대표전화1         응급실전화          진료시간(월요일)C  진료시간(화요일)C  진료시간(수요일)C  진료시간(목요일)C  진료시간(금요일)C  진료시간(토요일)C  진료시간(일요일)C  진료시간(공휴일)C  진료시간(월요일)S  진료시간(화요일)S  진료시간(수요일)S  진료시간(목요일)S  진료시간(금요일)S  진료시간(토요일)S  진료시간(일요일)S  진료시간(공휴일)S  우편번호1  우편번호2  병원경도        병원위도       작업시간
A1100001  서울특별시 동대문구 경희대로 23 (회기동)                      A     종합병원   G006      지역응급의료센터   1             10/1 (화) 임시공휴일, 10/3 (목) 개천절 : 09:30-13:00    서울대입구역 2번 출구 100 미터 이내입니다 . 지하2층에 주차장 있읍니다 .                                                                                                     영등포역 4번출구 파리바게트 건물    경희대학교병원        02-958-8114   02-958-8114    1730        1730        1730        1730        1730        1230.0      1800.0      1500.0      830         830         830         830         830         900.0       900.0       1000.0      24     47     127.051832  37.593877  2025-01-07 15:10:31.0    1
A1122584  서울특별시 성북구 동소문로 304, 3층 (하월곡동)                 N     치과의원   G099      응급의료기관 이외  2             점심시간 13:00~14:00                              발, 발목, 무릎, 어깨 상지 , 척추 특화 진료                                                                                                                      삼성래미안4차 상가 201호       연세고마운치과의원      02-917-2828   070-4698-7811  2030        1830        2030        1830        1830        1400.0      1900.0      1300.0      930         930         930         930         930         900.0       800.0       900.0       27     33     127.028677  37.606911  2025-01-07 15:10:51.0    1
A1122603  서울특별시 송파구 풍성로 52, 상가동 1층 16,17호 (풍납동, 대아아파트)  C     의원     G099      응급의료기관 이외  2             점심시간 13:00~14:00                              성북구 장위동에 위치한 가정의학과입니다.                                                                                                                           거여역 5번출구              아산사랑의원         02-485-8508   070-4698-7811  1800        1800        1800        1800        1800        1300.0      1300.0      1300.0      900         900         900         900         900         900.0       900.0       900.0       55     28     127.118098  37.533481  2025-01-07 15:10:49.0    1
A1122602  서울특별시 서초구 잠원로3길 40, 태남홀딩스 307호 (잠원동)          C     의원     G099      응급의료기관 이외  2             매월 마지막 토요일은 휴진                                점심시간 13:00~14:20                                                                                                                                 성대시장 안, 안일약국 건물 2층    삼성공감정신건강의학과의원  02-599-3303   02-880-0119    1830        1830        1400        1930        1830        1400.0      1400.0      1700.0      930         930         930         930         930         930.0       930.0       1030.0      65     10     127.003659  37.508213  2025-01-07 15:10:43.0    1
A1122601  서울특별시 종로구 새문안로3길 15, 동원빌딩 2층 (당주동)            C     의원     G099      응급의료기관 이외  2             점심시간 14:00-15:00                              피부 미용, 일반 피부과 진료 보톡스, 필러                                                                                                                         압구정역 3번출구             라움정신건강의학과의원    02-722-7779   02-829-9129    2000        2000        2000        2000        2000        1800.0      1800.0      1800.0      1000        1000        1000        1000        1000        1000.0      1100.0      1100.0      31     75     126.972301  37.571706  2025-01-07 15:10:37.0    1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ..
A1109257  서울특별시 중구 충무로 75, 5층 (입정동, 효봉빌딩)               N     치과의원   G099      응급의료기관 이외  2             호스피스O/중환자실O/인공호흡기O                            내 가족처럼 성심껏 진료하는 서울홍치과입니다.                                                                                                                        을지로3가역 4번 출구          서울훈치과의원        02-2266-3803  02-902-9119    1830        1830        1830        1830        1830        1400.0      1400.0      1400.0      930         930         930         930         930         930.0       1000.0      900.0       45     43     126.992181  37.567938  2021-06-07 14:55:02.0    1
A1109256  서울특별시 중구 다산로 106, 한두빌딩 4층 (신당동)               N     치과의원   G099      응급의료기관 이외  2             토요일2.4째주만진료, 2,4,5째주 목요일 휴진 / 수요일 야간진료        토요일2.4째주만진료                                                                                                                                      약수역 7번출구 4층, 영유아검진가능  이잘하는치과의원       02-757-7528   02-901-3119    1800        1800        2100        1800        1800        1400.0      1500.0      1500.0      1000        1400        1400        1000        1000        1000.0      900.0       900.0       45     97     127.010081  37.553348  2025-01-07 15:10:56.0    1
A1109255  서울특별시 강북구 노해로 74 (수유동, 임치과의원)                 N     치과의원   G099      응급의료기관 이외  2             월수목 09:00~18:00 화금 09:00~19:00 토 09:00~13:00  미아리고개에 위치한 성북구 동암동 삼성아파트 상가 3층에 있습니다. 버스정류장 명칭은 미아리고개입니다. 예약제로 운영되므로 예약없이 방문시 진료를 받지 못할 수도 있습니다. 반드시 전화로 예약하시고, 휴무일 꼭 확인하시고 오세요. 전화 02-923-5505  광산사거리                 임치과의원          02-993-8924   02-950-1119    1800        1800        1800        1800        1800        1300.0      1530.0      1700.0      930         930         930         930         930         930.0       1100.0      1000.0      10     70     127.022609  37.642113  2025-01-07 15:10:56.0    1
A1109254  서울특별시 성북구 오패산로 20, 지상2층 (하월곡동)                N     치과의원   G099      응급의료기관 이외  2             점심시간 13:00~14:00                              미용성형 위주                                                                                                                                          신사역 1번 출구 인근, 지하1층    훈치과의원          02-943-2820   02-2600-0777   1830        1830        1830        1830        1830        1600.0      1700.0      1400.0      930         930         930         930         930         930.0       1100.0      930.0       27     51     127.037790  37.604036  2025-01-07 15:11:03.0    1
G1100040  서울특별시 중구 서소문로 133, 2층 (서소문동)                  I     기타     G099      응급의료기관 이외  2             점심시간 13:00~14:00                              이물제거/수액/후두내시경/축농증수술/알레르기검사/후각미각검사                                                                                                                둔촌메디컬타워 6층            둥지조산원          02-303-5315   02-829-9129    2400        2400        2400        2400        2400        2400.0      2400.0      2400.0      0           0           0           0           0           0.0         0.0         0.0         45     15     126.975549  37.563891  2025-01-07 15:10:36.0    1
Name: count, Length: 20929, dtype: int64

In [3]:
import pandas as pd

df = pd.read_csv("./scaleResult3.csv")
df.head()
df = df.dropna(subset=['homeKind'])
print(df['homeKind'].isnull().sum())  # 0이면 성공적으로 제거됨
df.to_csv("scaleResult3.csv", index=False, encoding="utf-8-sig")

0